Prevent UdpQuacker from sending an empty quack
Previously this was causing tests such as
test_media_client_quacker_receives_resets to hang because the client
would try to send this quACK and panic on an unwrap.

[SIDEKICK:DEBUG] thread 'tokio-runtime-worker' panicked at /users/ygina/sidekick-downloads/deps/quack/src/power_sum.rs:214:52:
[SIDEKICK:DEBUG] called `Option::unwrap()` on a `None` value
[SIDEKICK:DEBUG] stack backtrace:
[SIDEKICK:DEBUG] 0: rust_begin_unwind
[SIDEKICK:DEBUG] 1: core::panicking::panic_fmt
[SIDEKICK:DEBUG] 2: core::panicking::panic
[SIDEKICK:DEBUG] 3: core::option::unwrap_failed
[SIDEKICK:DEBUG] 4: quack::QuackWrapper::serialize
[SIDEKICK:DEBUG] 5: <quacker::udp_quacker::UdpQuacker as quacker::quacker::Quacker>::send_quack
[SIDEKICK:DEBUG] 6: endpoint::main::{{closure}}::{{closure}}
[SIDEKICK:DEBUG] 7: tokio::runtime::task::core::Core<T,S>::poll
[SIDEKICK:DEBUG] 8: tokio::runtime::task::harness::Harness<T,S>::poll
[SIDEKICK:DEBUG] 9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
[SIDEKICK:DEBUG] 10: tokio::runtime::scheduler::multi_thread::worker::Context::run
[SIDEKICK:DEBUG] 11: tokio::runtime::context::set_scheduler
[SIDEKICK:DEBUG] 12: tokio::runtime::context::runtime::enter_runtime
[SIDEKICK:DEBUG] 13: tokio::runtime::scheduler::multi_thread::worker::run
[SIDEKICK:DEBUG] 14: std::panicking::try
[SIDEKICK:DEBUG] 15: tokio::runtime::task::harness::Harness<T,S>::poll
[SIDEKICK:DEBUG] 16: tokio::runtime::blocking::pool::Inner::run
[SIDEKICK:DEBUG] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.